### PR TITLE
Review Suggestions

### PR DESCRIPTION
**Pull request by nkelber**
A quick review of Pandas 1

### CODE REVIEW

**Comment by nkelber** [comment]
A few quick comments.

1. Can the CC BY citation at the top of the lesson link to the source repos instead of the personal websites?
2. The failed banks .csv did not properly download for me. I did not see it in the S3 server.
3. Downloading the .xslx file requires `openpyxl`. Maybe we should ask Matt and Ian to install. Otherwise, you'll need a `!pip install openpyxl` for the code to work.
4. The file reading directions for .csv and .xslx kind of interrupts the flow of the lesson. Would it make more sense at the end of the lesson or in a different lesson?

**Comment by nkelber** [comment]
I've also taken a look at pandas 2 now. I see that the issue with the failed banks .csv is actually a filename change. That should be an easy change. 

As for Pandas 2, I don't have significant change suggestions, but I think we should discuss what are the best things to teach in regards to two topics:

1. Using an assignment statement to change dataframes vs. using `inplace=True`
2. Using bracket vs. dot notation

I think there are compelling reasons to teach a little of both, but also compelling reasons to simplify and just teach one. My gut reaction is to leave out `inplace=True` and dot notation, but I know people will also encounter them in the wild. So maybe it is a disservice to pretend like they don't exist.

**Comment by czcindy426** [comment]
> A few quick comments.
> 
> 1. Can the CC BY citation at the top of the lesson link to the source repos instead of the personal websites?

I have changed the links to the source repo. 

> 2. The failed banks .csv did not properly download for me. I did not see it in the S3 server.

I have corrected the mistake. The file name has been changed on AWS but I didn't update it in Pandas1. 

> 3. Downloading the .xslx file requires `openpyxl`. Maybe we should ask Matt and Ian to install. Otherwise, you'll need a `!pip install openpyxl` for the code to work.

I have added a line to download this library. 

> 4. The file reading directions for .csv and .xslx kind of interrupts the flow of the lesson. Would it make more sense at the end of the lesson or in a different lesson?

I have moved this section to the end of the notebook.

**Comment by czcindy426** [comment]
> I've also taken a look at pandas 2 now. I see that the issue with the failed banks .csv is actually a filename change. That should be an easy change.
> 
> As for Pandas 2, I don't have significant change suggestions, but I think we should discuss what are the best things to teach in regards to two topics:
> 
> 1. Using an assignment statement to change dataframes vs. using `inplace=True`

I'll make sure to update all example with inplace=True. 

> 2. Using bracket vs. dot notation
> 
> I think there are compelling reasons to teach a little of both, but also compelling reasons to simplify and just teach one. My gut reaction is to leave out `inplace=True` and dot notation, but I know people will also encounter them in the wild. So maybe it is a disservice to pretend like they don't exist.

I'll remove the dot notation example. I'll perhaps briefly mention it in class.

**Pull request merged**
