### PR TITLE
Reorganization of notebook directories

### PR DESCRIPTION
**Pull request by czcindy426**
Reorganized the repo based on user feedback (STAR-262)

### CODE REVIEW

**Comment by nkelber** [comment]
I'm seeing some broken links, for example the "Start Python Basics" links in the top metadata. Take a look at Pandas-Intermediate-1.ipynb.

**Comment by nkelber** [comment]
The pytest link check would be useful for this: https://github.com/jupyterlab/pytest-check-links

**Comment by czcindy426** [comment]
I've checked the links using pytest-check-links. Let me know if you noticed anything else.

**Comment by iandesj** [comment]
> I've checked the links using pytest-check-links. Let me know if you noticed anything else.

I think the next requirement for this change is new links for the Tutorials ghost page. We should get those drafted up so we can coordinate the sequence of events, which will look something like...
1. Merge this branch
2. Merge the frontend changes into test
3. Update the Ghost post with new links
4. Test
5. Once we confirm everything works, promote to Prod. Hopefully steps 1-4 can happen in quick succession. We could put a banner up warning users that Tutorials may be out of date/in maintenance for a brief point in time.

Thoughts? A change of this type unfortunately involves some coordination.

**Review by nkelber — APPROVED** [review]
This looks good to me.

**Pull request merged**
